name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  flutter_lints: ^3.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.9.1
  bloc: ^8.1.2
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
